### ISSUE TITLE
TreePanel should scroll to allow most visibility

### ISSUE THREAD

**Issue by liamhays** [parkhays/MCBuzzer#7]
Wx has a ScrolledPanel widget, which will probably work fine. A scrollbar would make it easy to neglect testing on various screens.

**Comment by parkhays** [comment]
Scrolling is not functional on my laptop in the sense that it doesn't need to scroll to fit in the window, but the scrolling makes the panel area larger than the screen, and consequently make the interaction awful.

I think this change is not a good approach. Test the sizing without the change, if and only if that fails to fit everything across multiple screen sizes. For now, I am manually commenting out these changes.

**Comment by parkhays** [comment]
Reject this change. We tried it, but the scroll bars use too much real estate in low-resolution 600x800 displays. Backed out edits and used a font size change to control the display #1
